name: Build and deploy to GHP

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip
      
      - name: Install Python requirements
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements.txt

      - name: Default GFortran info
        run: |
          gfortran --version
          echo $(which gfortran)

      - name: Ensure default GFortran is v11 (link to `/usr/bin/gfortran`)
        run: |
          sudo ln -sf $(which gfortran-11) /usr/bin/gfortran
          gfortran --version

      - name: Generate MD
        run: python fortrantip.py all

      - name: Sphinx linkcheck
        run: sphinx-build -b linkcheck docs docs/_build/linkcheck

      - name: Sphinx build
        run: sphinx-build -b html -W docs docs/_build/html

      - name: Push built HTML to GHP
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./docs/_build/html
          git-config-name: github-actions
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          clean: true
          clean-exclude: .nojekyll  # default      
