name: Build and deploy to GHP

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: pip
      
      - name: Install Python requirements
        run: pip install -r requirements.txt

      - name: Default GFortran info
        run: |
          gfortran --version
          echo $(which gfortran)

      - name: Install GFortran v11 and link to `/usr/bin/gfortran`
        run: |
          sudo apt install gfortran-11
          sudo ln -sf $(which gfortran-11) /usr/bin/gfortran
          gfortran --version

      - name: Generate MD
        run: python fortrantip.py

      - name: Sphinx linkcheck
        run: sphinx-build -b linkcheck docs docs/_build/linkcheck

      - name: Sphinx build
        run: sphinx-build -b html -W docs docs/_build/html

      # - name: Push built HTML to GHP
      #   uses: JamesIves/github-pages-deploy-action@4.1.9
      #    with:
      #      branch: gh-pages
      #      folder: ./docs/_build/html
      #      git-config-name: github-actions
      #      git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
      #      clean: true
      #      clean-exclude: .nojekyll  # default      
